[pytest]
markers=
    unit: mark a test as a unit test
    integration: mark a test as an integration test
    always: mark a test as an integration test that should always run
filterwarnings =
    ignore::DeprecationWarning

log_cli = true
